DROP DATABASE IF EXISTS COOP;

CREATE DATABASE COOP;

USE COOP;


CREATE TABLE Customer (
	cid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR (256) NOT NULL,
	email VARCHAR (256) NOT NULL,
	studentNum INT UNSIGNED NOT NULL,
	building VARCHAR (256) NOT NULL,
	room INT UNSIGNED NOT NULL
);

CREATE TABLE PurchaseOrder (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cid INT UNSIGNED NOT NULL
);

CREATE TABLE Food (
	orderid INT UNSIGNED NOT NULL,
	type VARCHAR (256) NOT NULL,
	quantity INT UNSIGNED NOT NULL,
	price INT UNSIGNED NOT NULL
);

